name: ncbi-cluster-tracker
channels:
  - plotly
  - bioconda
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - conda-forge::google-cloud-bigquery=3.27.0
  - plotly=5.24.1
  - biopython=1.78
  - dendropy=5.0.1
  - mypy=1.11.2
  - types-requests=2.30.0.0
  - pandas-stubs=2.1.4.231227
  - pip=24.2
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - arakawa==0.0.9a3
      - base64io==1.0.3
      - chardet==5.2.0
      - dominate==2.9.1
      - ipynbname==2024.1.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - loguru==0.7.3
      - lxml==5.3.0
      - micawber==0.5.6
      - multimethod==2.0
      - narwhals==1.17.0
      - pyarrow==18.1.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pyhumps==3.8.0
      - referencing==0.35.1
      - rpds-py==0.22.3
      - semver==3.0.2
